"""empty message

Revision ID: 0e5de4e3b105
Revises: dad86d597b1b
Create Date: 2025-11-04 10:19:48.064830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5de4e3b105'
down_revision: Union[str, Sequence[str], None] = 'dad86d597b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subjects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='unique')
    # ### end Alembic commands ###
