"""empty message

Revision ID: 4dad3dd2ad23
Revises: d21a4e7b430c
Create Date: 2025-11-03 18:34:43.360153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dad3dd2ad23'
down_revision: Union[str, Sequence[str], None] = 'd21a4e7b430c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('mark', sa.Integer(), nullable=True))
    op.drop_column('students', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('students', 'mark')
    # ### end Alembic commands ###
